-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module CrossfitHistory.Object.Workout exposing (..)

import CrossfitHistory.InputObject
import CrossfitHistory.Interface
import CrossfitHistory.Object
import CrossfitHistory.Scalar
import CrossfitHistory.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) CrossfitHistory.Object.Workout
selection constructor =
    Object.selection constructor


id : Field CrossfitHistory.Scalar.Id CrossfitHistory.Object.Workout
id =
    Object.fieldDecoder "id" [] (Decode.oneOf [ Decode.string, Decode.float |> Decode.map toString, Decode.int |> Decode.map toString, Decode.bool |> Decode.map toString ] |> Decode.map CrossfitHistory.Scalar.Id)


occurred_on : Field String CrossfitHistory.Object.Workout
occurred_on =
    Object.fieldDecoder "occurred_on" [] Decode.string


primary : Field String CrossfitHistory.Object.Workout
primary =
    Object.fieldDecoder "primary" [] Decode.string


primary_modifiers : SelectionSet decodesTo CrossfitHistory.Object.Movement -> Field (List decodesTo) CrossfitHistory.Object.Workout
primary_modifiers object =
    Object.selectionField "primary_modifiers" [] object (identity >> Decode.list)


primary_movements : SelectionSet decodesTo CrossfitHistory.Object.Movement -> Field (List decodesTo) CrossfitHistory.Object.Workout
primary_movements object =
    Object.selectionField "primary_movements" [] object (identity >> Decode.list)


score : Field (Maybe String) CrossfitHistory.Object.Workout
score =
    Object.fieldDecoder "score" [] (Decode.string |> Decode.nullable)


secondary : Field (Maybe String) CrossfitHistory.Object.Workout
secondary =
    Object.fieldDecoder "secondary" [] (Decode.string |> Decode.nullable)


secondary_modifiers : SelectionSet decodesTo CrossfitHistory.Object.Movement -> Field (List decodesTo) CrossfitHistory.Object.Workout
secondary_modifiers object =
    Object.selectionField "secondary_modifiers" [] object (identity >> Decode.list)


secondary_movements : SelectionSet decodesTo CrossfitHistory.Object.Movement -> Field (List decodesTo) CrossfitHistory.Object.Workout
secondary_movements object =
    Object.selectionField "secondary_movements" [] object (identity >> Decode.list)


workout_url : Field (Maybe String) CrossfitHistory.Object.Workout
workout_url =
    Object.fieldDecoder "workout_url" [] (Decode.string |> Decode.nullable)
