-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module CrossfitHistory.Object exposing (..)


type Movement
    = Movement


type Workout
    = Workout
