-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module CrossfitHistory.Enum.MovementType exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The groups for movements
-}
type MovementType
    = Amrap
    | Cluster
    | Unbroken
    | Jerk
    | PowerClean
    | SquatClean
    | HangPowerClean
    | HangSquatClean
    | Thruster
    | SumoDeadlift
    | CleanGripDeadlift
    | Deadlift
    | BackSquat
    | FrontSquat
    | OhSquat
    | WeightedStrictCtb
    | CtbPullUp
    | StrictPullUp
    | WeightedPullUp
    | WeightedStrictRingDip
    | WeightedRingDip
    | ElevatedRingRow
    | ToughRingRow
    | CloseGripFloorPress
    | PowerSnatch
    | SquatSnatch
    | SnatchPull
    | StrictDeficitHspu
    | StrictHspu
    | CloseGripBenchPress
    | CloseGripBench
    | BenchPress
    | SupinatedGripBentOverBbRow
    | SingleArmDbKbBentOverRow
    | SaDbBentOverRow
    | FrontRackStepUp
    | FrontRackBbStepUp
    | FrontRackBbRfeSplitSquat
    | FrontRackRfeSplitSquat
    | BtnShoulderPress
    | PushPress
    | ShoulderPress
    | LeglessRc
    | RopeClimb
    | Rc
    | RopePull
    | InclineDbKbProneRowOnBench
    | SupineRowToChest
    | BarFacingBurpee
    | BurpeeBoxJumpStepDown
    | BurpeeBoxJump
    | BurpeesToTarget
    | BoxJumpStepDown
    | DoubleUndersSingleUnders
    | DoubleUnders
    | WallBall
    | MuscleUp
    | CalRow
    | ShoulderToOverhead
    | ShuttleRun
    | LSeatedDbPress
    | Run
    | MRow
    | FarmerHold
    | Ttb
    | DiamondPushUp
    | PushUp


decoder : Decoder MovementType
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "AMRAP" ->
                        Decode.succeed Amrap

                    "CLUSTER" ->
                        Decode.succeed Cluster

                    "UNBROKEN" ->
                        Decode.succeed Unbroken

                    "JERK" ->
                        Decode.succeed Jerk

                    "POWER_CLEAN" ->
                        Decode.succeed PowerClean

                    "SQUAT_CLEAN" ->
                        Decode.succeed SquatClean

                    "HANG_POWER_CLEAN" ->
                        Decode.succeed HangPowerClean

                    "HANG_SQUAT_CLEAN" ->
                        Decode.succeed HangSquatClean

                    "THRUSTER" ->
                        Decode.succeed Thruster

                    "SUMO_DEADLIFT" ->
                        Decode.succeed SumoDeadlift

                    "CLEAN_GRIP_DEADLIFT" ->
                        Decode.succeed CleanGripDeadlift

                    "DEADLIFT" ->
                        Decode.succeed Deadlift

                    "BACK_SQUAT" ->
                        Decode.succeed BackSquat

                    "FRONT_SQUAT" ->
                        Decode.succeed FrontSquat

                    "OH_SQUAT" ->
                        Decode.succeed OhSquat

                    "WEIGHTED_STRICT_CTB" ->
                        Decode.succeed WeightedStrictCtb

                    "CTB_PULL_UP" ->
                        Decode.succeed CtbPullUp

                    "STRICT_PULL_UP" ->
                        Decode.succeed StrictPullUp

                    "WEIGHTED_PULL_UP" ->
                        Decode.succeed WeightedPullUp

                    "WEIGHTED_STRICT_RING_DIP" ->
                        Decode.succeed WeightedStrictRingDip

                    "WEIGHTED_RING_DIP" ->
                        Decode.succeed WeightedRingDip

                    "ELEVATED_RING_ROW" ->
                        Decode.succeed ElevatedRingRow

                    "TOUGH_RING_ROW" ->
                        Decode.succeed ToughRingRow

                    "CLOSE_GRIP_FLOOR_PRESS" ->
                        Decode.succeed CloseGripFloorPress

                    "POWER_SNATCH" ->
                        Decode.succeed PowerSnatch

                    "SQUAT_SNATCH" ->
                        Decode.succeed SquatSnatch

                    "SNATCH_PULL" ->
                        Decode.succeed SnatchPull

                    "STRICT_DEFICIT_HSPU" ->
                        Decode.succeed StrictDeficitHspu

                    "STRICT_HSPU" ->
                        Decode.succeed StrictHspu

                    "CLOSE_GRIP_BENCH_PRESS" ->
                        Decode.succeed CloseGripBenchPress

                    "CLOSE_GRIP_BENCH" ->
                        Decode.succeed CloseGripBench

                    "BENCH_PRESS" ->
                        Decode.succeed BenchPress

                    "SUPINATED_GRIP_BENT_OVER_BB_ROW" ->
                        Decode.succeed SupinatedGripBentOverBbRow

                    "SINGLE_ARM_DB_KB_BENT_OVER_ROW" ->
                        Decode.succeed SingleArmDbKbBentOverRow

                    "SA_DB_BENT_OVER_ROW" ->
                        Decode.succeed SaDbBentOverRow

                    "FRONT_RACK_STEP_UP" ->
                        Decode.succeed FrontRackStepUp

                    "FRONT_RACK_BB_STEP_UP" ->
                        Decode.succeed FrontRackBbStepUp

                    "FRONT_RACK_BB_RFE_SPLIT_SQUAT" ->
                        Decode.succeed FrontRackBbRfeSplitSquat

                    "FRONT_RACK_RFE_SPLIT_SQUAT" ->
                        Decode.succeed FrontRackRfeSplitSquat

                    "BTN_SHOULDER_PRESS" ->
                        Decode.succeed BtnShoulderPress

                    "PUSH_PRESS" ->
                        Decode.succeed PushPress

                    "SHOULDER_PRESS" ->
                        Decode.succeed ShoulderPress

                    "LEGLESS_RC" ->
                        Decode.succeed LeglessRc

                    "ROPE_CLIMB" ->
                        Decode.succeed RopeClimb

                    "RC" ->
                        Decode.succeed Rc

                    "ROPE_PULL" ->
                        Decode.succeed RopePull

                    "INCLINE_DB_KB_PRONE_ROW_ON_BENCH" ->
                        Decode.succeed InclineDbKbProneRowOnBench

                    "SUPINE_ROW_TO_CHEST" ->
                        Decode.succeed SupineRowToChest

                    "BAR_FACING_BURPEE" ->
                        Decode.succeed BarFacingBurpee

                    "BURPEE_BOX_JUMP_STEP_DOWN" ->
                        Decode.succeed BurpeeBoxJumpStepDown

                    "BURPEE_BOX_JUMP" ->
                        Decode.succeed BurpeeBoxJump

                    "BURPEES_TO_TARGET" ->
                        Decode.succeed BurpeesToTarget

                    "BOX_JUMP_STEP_DOWN" ->
                        Decode.succeed BoxJumpStepDown

                    "DOUBLE_UNDERS_SINGLE_UNDERS" ->
                        Decode.succeed DoubleUndersSingleUnders

                    "DOUBLE_UNDERS" ->
                        Decode.succeed DoubleUnders

                    "WALL_BALL" ->
                        Decode.succeed WallBall

                    "MUSCLE_UP" ->
                        Decode.succeed MuscleUp

                    "CAL_ROW" ->
                        Decode.succeed CalRow

                    "SHOULDER_TO_OVERHEAD" ->
                        Decode.succeed ShoulderToOverhead

                    "SHUTTLE_RUN" ->
                        Decode.succeed ShuttleRun

                    "L_SEATED_DB_PRESS" ->
                        Decode.succeed LSeatedDbPress

                    "RUN" ->
                        Decode.succeed Run

                    "M_ROW" ->
                        Decode.succeed MRow

                    "FARMER_HOLD" ->
                        Decode.succeed FarmerHold

                    "TTB" ->
                        Decode.succeed Ttb

                    "DIAMOND_PUSH_UP" ->
                        Decode.succeed DiamondPushUp

                    "PUSH_UP" ->
                        Decode.succeed PushUp

                    _ ->
                        Decode.fail ("Invalid MovementType type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : MovementType -> String
toString enum =
    case enum of
        Amrap ->
            "AMRAP"

        Cluster ->
            "CLUSTER"

        Unbroken ->
            "UNBROKEN"

        Jerk ->
            "JERK"

        PowerClean ->
            "POWER_CLEAN"

        SquatClean ->
            "SQUAT_CLEAN"

        HangPowerClean ->
            "HANG_POWER_CLEAN"

        HangSquatClean ->
            "HANG_SQUAT_CLEAN"

        Thruster ->
            "THRUSTER"

        SumoDeadlift ->
            "SUMO_DEADLIFT"

        CleanGripDeadlift ->
            "CLEAN_GRIP_DEADLIFT"

        Deadlift ->
            "DEADLIFT"

        BackSquat ->
            "BACK_SQUAT"

        FrontSquat ->
            "FRONT_SQUAT"

        OhSquat ->
            "OH_SQUAT"

        WeightedStrictCtb ->
            "WEIGHTED_STRICT_CTB"

        CtbPullUp ->
            "CTB_PULL_UP"

        StrictPullUp ->
            "STRICT_PULL_UP"

        WeightedPullUp ->
            "WEIGHTED_PULL_UP"

        WeightedStrictRingDip ->
            "WEIGHTED_STRICT_RING_DIP"

        WeightedRingDip ->
            "WEIGHTED_RING_DIP"

        ElevatedRingRow ->
            "ELEVATED_RING_ROW"

        ToughRingRow ->
            "TOUGH_RING_ROW"

        CloseGripFloorPress ->
            "CLOSE_GRIP_FLOOR_PRESS"

        PowerSnatch ->
            "POWER_SNATCH"

        SquatSnatch ->
            "SQUAT_SNATCH"

        SnatchPull ->
            "SNATCH_PULL"

        StrictDeficitHspu ->
            "STRICT_DEFICIT_HSPU"

        StrictHspu ->
            "STRICT_HSPU"

        CloseGripBenchPress ->
            "CLOSE_GRIP_BENCH_PRESS"

        CloseGripBench ->
            "CLOSE_GRIP_BENCH"

        BenchPress ->
            "BENCH_PRESS"

        SupinatedGripBentOverBbRow ->
            "SUPINATED_GRIP_BENT_OVER_BB_ROW"

        SingleArmDbKbBentOverRow ->
            "SINGLE_ARM_DB_KB_BENT_OVER_ROW"

        SaDbBentOverRow ->
            "SA_DB_BENT_OVER_ROW"

        FrontRackStepUp ->
            "FRONT_RACK_STEP_UP"

        FrontRackBbStepUp ->
            "FRONT_RACK_BB_STEP_UP"

        FrontRackBbRfeSplitSquat ->
            "FRONT_RACK_BB_RFE_SPLIT_SQUAT"

        FrontRackRfeSplitSquat ->
            "FRONT_RACK_RFE_SPLIT_SQUAT"

        BtnShoulderPress ->
            "BTN_SHOULDER_PRESS"

        PushPress ->
            "PUSH_PRESS"

        ShoulderPress ->
            "SHOULDER_PRESS"

        LeglessRc ->
            "LEGLESS_RC"

        RopeClimb ->
            "ROPE_CLIMB"

        Rc ->
            "RC"

        RopePull ->
            "ROPE_PULL"

        InclineDbKbProneRowOnBench ->
            "INCLINE_DB_KB_PRONE_ROW_ON_BENCH"

        SupineRowToChest ->
            "SUPINE_ROW_TO_CHEST"

        BarFacingBurpee ->
            "BAR_FACING_BURPEE"

        BurpeeBoxJumpStepDown ->
            "BURPEE_BOX_JUMP_STEP_DOWN"

        BurpeeBoxJump ->
            "BURPEE_BOX_JUMP"

        BurpeesToTarget ->
            "BURPEES_TO_TARGET"

        BoxJumpStepDown ->
            "BOX_JUMP_STEP_DOWN"

        DoubleUndersSingleUnders ->
            "DOUBLE_UNDERS_SINGLE_UNDERS"

        DoubleUnders ->
            "DOUBLE_UNDERS"

        WallBall ->
            "WALL_BALL"

        MuscleUp ->
            "MUSCLE_UP"

        CalRow ->
            "CAL_ROW"

        ShoulderToOverhead ->
            "SHOULDER_TO_OVERHEAD"

        ShuttleRun ->
            "SHUTTLE_RUN"

        LSeatedDbPress ->
            "L_SEATED_DB_PRESS"

        Run ->
            "RUN"

        MRow ->
            "M_ROW"

        FarmerHold ->
            "FARMER_HOLD"

        Ttb ->
            "TTB"

        DiamondPushUp ->
            "DIAMOND_PUSH_UP"

        PushUp ->
            "PUSH_UP"
